<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="keywords" content="openstreetmap routino verifier">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, user-scalable=no">

<title>Routino : Vizualizér údajov pre smerovanie údajov</title>

<!--
Routino data visualiser web page.

Part of the Routino routing software.

This file Copyright 2008-2017 Andrew M. Bishop

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
-->

<!-- Page elements -->
<script src="page-elements.js" type="text/javascript"></script>
<link href="page-elements.css" type="text/css" rel="stylesheet">

<!-- Router and visualiser shared features -->
<link href="maplayout.css" type="text/css" rel="stylesheet">

<!-- Visualiser specific features -->
<script src="mapprops.js" type="text/javascript"></script>
<link href="visualiser.css" type="text/css" rel="stylesheet">

<!-- Map parameters -->
<script src="mapprops.js" type="text/javascript"></script>

<!-- Map loader -->
<script src="maploader.js" type="text/javascript"></script>

</head>
<body onload="map_load('map_init();');">

<!-- Left hand side of window - data panel -->

<div class="left_panel">

<div class="tab_box">
<span id="tab_visualiser" onclick="tab_select('visualiser');" class="tab_selected" title="Select data options">Visualiser</span>
<span id="tab_router" onclick="tab_select('router');" class="tab_unselected" title="Plan a route">Router</span>
<span id="tab_data" onclick="tab_select('data');" class="tab_unselected" title="View database information">Data</span>
</div>

<div class="tab_content" id="tab_visualiser_div">

<div class="hideshow_box">
<span class="hideshow_title">Routino vizualizér</span>
Táto webová stránka umožňuje vizualizáciu údajov, ktoré Routino používa na smerovanie.
Zobrazujú sa iba tie údaje, ktoré sú relevantné pre smerovanie a preto niektoré údaje sú vylúčené.
<div class="center">
<a target="other" href="http://www.routino.org/">Webová stránka Routino</a>
|
<a target="other" href="documentation/">Dokumentácia</a>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_language_show" onclick="hideshow_show('language');" class="hideshow_show">+</span>
<span id="hideshow_language_hide" onclick="hideshow_hide('language');" class="hideshow_hide">-</span>
<span class="hideshow_title">Jazyk</span>

<div id="hideshow_language_div" style="display: none;">
<table>
<tr>
<td><a id="lang_en_url" href="visualiser.html.en" title="English language webpage">English</a>
<td>(EN)
<tr>
<td><a id="lang_cs_url" href="visualiser.html.cs" title="Stránka v češtině">Česky</a>
<td>(CS)
<tr>
<td><a id="lang_de_url" href="visualiser.html.de" title="Deutsche Webseite">Deutsch</a>
<td>(DE)
<tr>
<td><a id="lang_es_url" href="visualiser.html.es" title="Español webpage">Español</a>
<td>(ES)
<tr>
<td><a id="lang_fi_url" href="visualiser.html.fi" title="Suomi webpage">Suomi</a>
<td>(FI)
<tr>
<td><a id="lang_fr_url" href="visualiser.html.fr" title="Page web en français">Français</a>
<td>(FR)
<tr>
<td><a id="lang_hu_url" href="visualiser.html.hu" title="Magyar weboldal">Magyar</a>
<td>(HU)
<tr>
<td><a id="lang_it_url" href="visualiser.html.it" title="Italiano webpage">Italiano</a>
<td>(IT)
<tr>
<td><a id="lang_nl_url" href="visualiser.html.nl" title="Nederlandse web pagina">Nederlands</a>
<td>(NL)
<tr>
<td><a id="lang_pl_url" href="visualiser.html.pl" title="Polski webpage">Polski</a>
<td>(PL)
<tr>
<td><a id="lang_ru_url" href="visualiser.html.ru" title="Страница на русском языке">Русский</a>
<td>(RU)
<tr>
<td><a id="lang_sk_url" href="visualiser.html.sk" title="Stránka v slovenčine">Slovenčina</a>
<td>(SK)
</table>
<a target="translation" href="http://www.routino.org/translations/">Routino Translations</a>
</div>
</div>

<div class="hideshow_box">
<span class="hideshow_title">Inštrukcie</span>
Priblížte a potom pomocou tlačidiel nižšie stiahnite údaje. Server vráti údaje iba vtedy, ak je označená oblasť dostatočne malá.
</div>

<div class="hideshow_box">
<span class="hideshow_title">Stav</span>
<div id="result_status">
<div id="result_status_no_data">
<b><i>Nezobrazujú sa žiadne dáta</i></b>
</div>
<div id="result_status_data" style="display: none;">
</div>
<div id="result_status_failed" style="display: none;">
<b>Nepodarilo sa získať údaje vizualizéra!</b>
</div>
<div id="result_status_junctions" style="display: none;">
<b>Spracované # križovatky</b>
</div>
<div id="result_status_super" style="display: none;">
<b>Spracované # superuzly/segmenty</b>
</div>
<div id="result_status_waytype" style="display: none;">
<b>Spracované # cestné segmenty</b>
</div>
<div id="result_status_highway" style="display: none;">
<b>Spracované # segmenty</b>
</div>
<div id="result_status_transport" style="display: none;">
<b>Spracované # segmenty</b>
</div>
<div id="result_status_barrier" style="display: none;">
<b>Spracované # uzly</b>
</div>
<div id="result_status_turns" style="display: none;">
<b>Spracované # obmedzenia odbočení</b>
</div>
<div id="result_status_limit" style="display: none;">
<b>Spracované # zmeny rýchlostných obmedzení</b>
</div>
<div id="result_status_property" style="display: none;">
<b>Spracované # segmenty</b>
</div>
<div id="result_status_errorlogs" style="display: none;">
<b>Spracované # chyby</b>
</div>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_junctions_show" onclick="hideshow_show('junctions');" class="hideshow_show">+</span>
<span id="hideshow_junctions_hide" onclick="hideshow_hide('junctions');" class="hideshow_hide">-</span>
<input type="button" id="junctions" onclick="displayData('junctions');" value="Zobraz križovatky">
<div id="hideshow_junctions_div" style="display: none;">
Každý uzol, ktorý je slepou uličkou, križovatkou dvoch typov rôznych ciest (alebo rôznych vlastností), alebo križovatka, kde sa stretávajú viac ako dva segmenty, sú zobrazené farebne.
<br>
<table>
<tr><td><img src="icons/ball-1.png" alt="1" ><td>len jedna cesta - slepá ulička.
<tr><td><img src="icons/ball-2.png" alt="2" ><td>stret dvoch rôznych typov ciest.
<tr><td><img src="icons/ball-3.png" alt="3" ><td>stret troch ciest.
<tr><td><img src="icons/ball-4.png" alt="4" ><td>stret štyroch ciest.
<tr><td><img src="icons/ball-5.png" alt="5" ><td>stret piatich ciest.
<tr><td><img src="icons/ball-6.png" alt="6" ><td>stret šiestich ciest.
<tr><td><img src="icons/ball-7.png" alt="7+"><td>stret siedmych (alebo viac) ciest.
</table>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_super_show" onclick="hideshow_show('super');" class="hideshow_show">+</span>
<span id="hideshow_super_hide" onclick="hideshow_hide('super');" class="hideshow_hide">-</span>
<input type="button" id="super" onclick="displayData('super');" value="Zobraz Supersegmenty">
<div id="hideshow_super_div" style="display: none;">
Zobrazuje sa každý superuzol a súvisiace supersegmenty (pozri
stránku algoritmu pre podrobnejší popis).
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_waytype_show" onclick="hideshow_show('waytype');" class="hideshow_show">+</span>
<span id="hideshow_waytype_hide" onclick="hideshow_hide('waytype');" class="hideshow_hide">-</span>
<input type="button" id="waytype" onclick="displayData('waytype');" value="Zobraz cestné typy segmentov">
<div id="hideshow_waytype_div" style="display: none;">
Zobrazujeme každý diaľničný úsek špeciálneho typu (jednosmerný, obojsmerný pre cyklistov a kruhový objazd). Pre jednosmerné segmenty, farebný trojuholník označuje povolený smer.
Farby trojuholníkov závisia od smeru cestného segmentu.
<form name="waytypes" id="waytypes" action="#" method="get" onsubmit="return false;">
<table>
<tr><td>Jednosmerné segmenty: <td><input name="waytype" type="radio" value="oneway" onchange="displayData('waytype');" checked>
<tr><td>Cyklistické obojsmerné segmenty:<td><input name="waytype" type="radio" value="cyclebothways" onchange="displayData('waytype');">
<tr><td>Segmenty kruhových objazdov: <td><input name="waytype" type="radio" value="roundabout" onchange="displayData('waytype');">
</table>
</form>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_highway_show" onclick="hideshow_show('highway');" class="hideshow_show">+</span>
<span id="hideshow_highway_hide" onclick="hideshow_hide('highway');" class="hideshow_hide">-</span>
<input type="button" id="highway" onclick="displayData('highway');" value="Zobraz cestné segmenty">
<div id="hideshow_highway_div" style="display: none;">
Zakreslí sa každý segment zvoleného typu cesty.
<form name="highways" id="highways" action="#" method="get" onsubmit="return false;">
<table>
<tr><td>Diaľnica: <td><input name="highway" type="radio" value="motorway" onchange="displayData('highway');">
<tr><td>Hlavná cesta: <td><input name="highway" type="radio" value="trunk" onchange="displayData('highway');">
<tr><td>Cesta I. triedy: <td><input name="highway" type="radio" value="primary" onchange="displayData('highway');" checked>
<tr><td>Cesta II. triedy: <td><input name="highway" type="radio" value="secondary" onchange="displayData('highway');">
<tr><td>Cesta III. triedy: <td><input name="highway" type="radio" value="tertiary" onchange="displayData('highway');">
<tr><td>Neoznačená cesta:<td><input name="highway" type="radio" value="unclassified" onchange="displayData('highway');">
<tr><td>Miestna komunikácia: <td><input name="highway" type="radio" value="residential" onchange="displayData('highway');">
<tr><td>Účelová komunikácia: <td><input name="highway" type="radio" value="service" onchange="displayData('highway');">
<tr><td>Cesta: <td><input name="highway" type="radio" value="track" onchange="displayData('highway');">
<tr><td>Cyklocesta: <td><input name="highway" type="radio" value="cycleway" onchange="displayData('highway');">
<tr><td>Chodník: <td><input name="highway" type="radio" value="path" onchange="displayData('highway');">
<tr><td>Schody: <td><input name="highway" type="radio" value="steps" onchange="displayData('highway');">
<tr><td>Prievoz: <td><input name="highway" type="radio" value="ferry" onchange="displayData('highway');">
</table>
</form>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_transport_show" onclick="hideshow_show('transport');" class="hideshow_show">+</span>
<span id="hideshow_transport_hide" onclick="hideshow_hide('transport');" class="hideshow_hide">-</span>
<input type="button" id="transport" onclick="displayData('transport');" value="Zobraziť dopravné segmenty">
<div id="hideshow_transport_div" style="display: none;">
Vykreslí sa každý povolený segment pre zvolený typ dopravy.
<form name="transports" id="transports" action="#" method="get" onsubmit="return false;">
<table>
<tr><td>Pešo: <td><input name="transport" type="radio" value="foot" onchange="displayData('transport');">
<tr><td>Kôň: <td><input name="transport" type="radio" value="horse" onchange="displayData('transport');">
<tr><td>Invalidný vozík:<td><input name="transport" type="radio" value="wheelchair" onchange="displayData('transport');">
<tr><td>Bicykel: <td><input name="transport" type="radio" value="bicycle" onchange="displayData('transport');">
<tr><td>Moped: <td><input name="transport" type="radio" value="moped" onchange="displayData('transport');">
<tr><td>Motorka:<td><input name="transport" type="radio" value="motorcycle" onchange="displayData('transport');">
<tr><td>Motorové vozidlo: <td><input name="transport" type="radio" value="motorcar" onchange="displayData('transport');" checked>
<tr><td>Nákladné vozidlo: <td><input name="transport" type="radio" value="goods" onchange="displayData('transport');">
<tr><td>Ťažké nákladné auto: <td><input name="transport" type="radio" value="hgv" onchange="displayData('transport');">
<tr><td>Verejná doprava: <td><input name="transport" type="radio" value="psv" onchange="displayData('transport');">
</table>
</form>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_barrier_show" onclick="hideshow_show('barrier');" class="hideshow_show">+</span>
<span id="hideshow_barrier_hide" onclick="hideshow_hide('barrier');" class="hideshow_hide">-</span>
<input type="button" id="barrier" onclick="displayData('barrier');" value="Zobraziť uzly bariéry">
<div id="hideshow_barrier_div" style="display: none;">
Vykreslí každú bariéru blokujúcu zvolený druh dopravy.
<form name="barriers" id="barriers" action="#" method="get" onsubmit="return false;">
<table>
<tr><td>Pešo: <td><input name="barrier" type="radio" value="foot" onchange="displayData('barrier');">
<tr><td>Kôň: <td><input name="barrier" type="radio" value="horse" onchange="displayData('barrier');">
<tr><td>Invalidný vozík:<td><input name="barrier" type="radio" value="wheelchair" onchange="displayData('barrier');">
<tr><td>Bicykel: <td><input name="barrier" type="radio" value="bicycle" onchange="displayData('barrier');">
<tr><td>Moped: <td><input name="barrier" type="radio" value="moped" onchange="displayData('barrier');">
<tr><td>Motorka:<td><input name="barrier" type="radio" value="motorcycle" onchange="displayData('barrier');">
<tr><td>Motorové vozidlo: <td><input name="barrier" type="radio" value="motorcar" onchange="displayData('barrier');" checked>
<tr><td>Nákladné vozidlo: <td><input name="barrier" type="radio" value="goods" onchange="displayData('barrier');">
<tr><td>Ťažké nákladné auto: <td><input name="barrier" type="radio" value="hgv" onchange="displayData('barrier');">
<tr><td>Verejná doprava: <td><input name="barrier" type="radio" value="psv" onchange="displayData('barrier');">
</table>
</form>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_turns_show" onclick="hideshow_show('turns');" class="hideshow_show">+</span>
<span id="hideshow_turns_hide" onclick="hideshow_hide('turns');" class="hideshow_hide">-</span>
<input type="button" id="turns" onclick="displayData('turns');" value="Zobraz obmedzenia odbočenia">
<div id="hideshow_turns_div" style="display: none;">
Každé obmedzenie odbočenia je znázornené čiarou označujúcou nepovolenú odbočku.
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_speed_show" onclick="hideshow_show('speed');" class="hideshow_show">+</span>
<span id="hideshow_speed_hide" onclick="hideshow_hide('speed');" class="hideshow_hide">-</span>
<input type="button" id="speed" onclick="displayData('speed');" value="Zobraz rýchlostné obmedzenia">
<div id="hideshow_speed_div" style="display: none;">
Je zobrazený každý uzol, ktorý spája segmenty s rôznymi rýchlostnými obmedzeniami spolu s rýchlostným obmedzením na príslušných úsekoch.
<br>
<table>
<tr><td><img src="icons/ball-1.png" alt="." ><td>Zmena rýchlostného obmedzenia
<tr><td><img src="icons/limit-no.png" alt="()" ><td>Nešpecifikované rýchlostné obmedzenie
<tr><td><img src="icons/limit-80.png" alt="(80)"><td>Rýchlostné obmedzenie na 80 km/h
</table>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_weight_show" onclick="hideshow_show('weight');" class="hideshow_show">+</span>
<span id="hideshow_weight_hide" onclick="hideshow_hide('weight');" class="hideshow_hide">-</span>
<input type="button" id="weight" onclick="displayData('weight');" value="Zobraz hmotnostné obmedzenia">
<div id="hideshow_weight_div" style="display: none;">
Je zobrazený každý uzol, ktorý spája segmenty s rôznymi hmotnostnými obmedzeniami spolu s hmotnostným obmedzením pre príslušné segmenty.
<br>
<table>
<tr><td><img src="icons/ball-1.png" alt="." ><td>Zmena rýchlostného obmedzenia
<tr><td><img src="icons/limit-no.png" alt="()" ><td>Nešpecifikované rýchlostné obmedzenie
<tr><td><img src="icons/limit-8.0.png" alt="(8.0)"><td>Hmotnostné obmedzenia do 8 ton.
</table>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_height_show" onclick="hideshow_show('height');" class="hideshow_show">+</span>
<span id="hideshow_height_hide" onclick="hideshow_hide('height');" class="hideshow_hide">-</span>
<input type="button" id="height" onclick="displayData('height');" value="Zobrazenie výškových obmedzení">
<div id="hideshow_height_div" style="display: none;">
Je zobrazený každý uzol, ktorý spája segmenty s rôznymi výškovými obmedzeniami spolu s výškovým obmedzením pre príslušné segmenty.
<br>
<table>
<tr><td><img src="icons/ball-1.png" alt="." ><td>Zmena rýchlostného obmedzenia
<tr><td><img src="icons/limit-no.png" alt="()" ><td>Nešpecifikované rýchlostné obmedzenie
<tr><td><img src="icons/limit-4.0.png" alt="(4.0)"><td>Obmedzenie výšky do 4.0 m.
</table>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_width_show" onclick="hideshow_show('width');" class="hideshow_show">+</span>
<span id="hideshow_width_hide" onclick="hideshow_hide('width');" class="hideshow_hide">-</span>
<input type="button" id="width" onclick="displayData('width');" value="Zobrazenie obmedzení šírky">
<div id="hideshow_width_div" style="display: none;">
Je zobrazený každý uzol, ktorý spája segmenty s rôznymi šírkovými obmedzeniami spolu so šírkovým obmedzením pre príslušné segmenty.
<br>
<table>
<tr><td><img src="icons/ball-1.png" alt="." ><td>Zmena rýchlostného obmedzenia
<tr><td><img src="icons/limit-no.png" alt="()" ><td>Nešpecifikované rýchlostné obmedzenie
<tr><td><img src="icons/limit-3.0.png" alt="(3.0)"><td>Obmedzenie šírky do 3.0 m.
</table>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_length_show" onclick="hideshow_show('length');" class="hideshow_show">+</span>
<span id="hideshow_length_hide" onclick="hideshow_hide('length');" class="hideshow_hide">-</span>
<input type="button" id="length" onclick="displayData('length');" value="Zobrazenie obmedzení dĺžky">
<div id="hideshow_length_div" style="display: none;">
Je zobrazený každý uzol, ktorý spája segmenty s rôznymi obmedzeniami dĺžky spolu s obmedzením dĺžky pre príslušné segmenty.
<br>
<table>
<tr><td><img src="icons/ball-1.png" alt="." ><td>Zmena rýchlostného obmedzenia
<tr><td><img src="icons/limit-no.png" alt="()" ><td>Nešpecifikované rýchlostné obmedzenie
<tr><td><img src="icons/limit-9.0.png" alt="(9.0)"><td>Obmedzenie dlžky do 9.0 m.
</table>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_property_show" onclick="hideshow_show('property');" class="hideshow_show">+</span>
<span id="hideshow_property_hide" onclick="hideshow_hide('property');" class="hideshow_hide">-</span>
<input type="button" id="property" onclick="displayData('property');" value="Zobraz vlastnosti cesty">
<div id="hideshow_property_div" style="display: none;">
Je vykreslený každý segment ciest s konkrétnou vlastnosťou.
<form name="properties" id="properties" action="#" method="get" onsubmit="return false;">
<table>
<tr><td>Dláždená: <td><input name="property" type="radio" value="paved" onchange="displayData('property');" checked>
<tr><td>Viac pruhov: <td><input name="property" type="radio" value="multilane" onchange="displayData('property');">
<tr><td>Most: <td><input name="property" type="radio" value="bridge" onchange="displayData('property');">
<tr><td>Tunel: <td><input name="property" type="radio" value="tunnel" onchange="displayData('property');">
<tr><td>Pešia trasa: <td><input name="property" type="radio" value="footroute" onchange="displayData('property');">
<tr><td>Cyklotrasa: <td><input name="property" type="radio" value="bicycleroute" onchange="displayData('property');">
</table>
</form>
</div>
</div>

<div class="hideshow_box">
<span id="hideshow_errorlogs_show" onclick="hideshow_show('errorlogs');" class="hideshow_show">+</span>
<span id="hideshow_errorlogs_hide" onclick="hideshow_hide('errorlogs');" class="hideshow_hide">-</span>
<input type="button" id="errorlogs" onclick="displayData('errorlogs');" value="Zobraz chyby">
<div id="hideshow_errorlogs_div" style="display: none;">
Potenciálne problémy nájdené Routinom pri spracovaní vstupných údajov.
</div>
</div>

<div class="hideshow_box">
<input type="button" id="clear" onclick="displayData('');" value="Vymaž údaje">
</div>

<div class="hideshow_box">
<span class="hideshow_title">Odkazy</span>
<a id="permalink_url" href="visualiser.html">Odkaz na túto mapu</a>
<br>
<a id="edit_url" target="edit" style="display: none;">Upraviť tieto OSM dáta</a>
</div>

<div class="hideshow_box">
<span id="hideshow_help_options_show" onclick="hideshow_show('help_options');" class="hideshow_hide">+</span>
<span id="hideshow_help_options_hide" onclick="hideshow_hide('help_options');" class="hideshow_show">-</span>
<span class="hideshow_title">Pomoc</span>
<div id="hideshow_help_options_div">
<div class="scrollable">
<b>Stručný návod</b>
<br>
Priblížte sa do oblasti a vyberte jedno z tlačidiel na zobrazenie daného typu
údajov.
<br>
Ďalšie možnosti údajov nájdete po rozbalení podrobností pod každým tlačidlom.
<p>
<b>Zlyhanie údajov</b>
<br>
Ak je vybratá oblasť príliš veľká (závisí od typu údajov), výsledný stav bude "Nepodarilo sa získať údaje vizualizéra" - priblížte sa viac a skúste
znova.
</div>
</div>
</div>
</div>

<div class="tab_content" id="tab_router_div" style="display: none;">
<div class="hideshow_box">
<span class="hideshow_title">Routino smerovač</span>
Ak chcete vykonať trasovanie na mape, použite odkaz nižšie.
<br>
<a id="router_url" href="router.html" target="router">Odkaz na túto mapu</a>
</div>
</div>

<div class="tab_content" id="tab_data_div" style="display: none;">
<div class="hideshow_box">
<span class="hideshow_title">Routino štatistiky</span>
<div id="statistics_data"></div>
<a id="statistics_link" href="statistics.cgi" onclick="displayStatistics();return(false);">Zobraz štatistiky</a>
</div>
</div>

</div>

<!-- Right hand side of window - map -->

<div class="right_panel">
<div class="map" id="map">
<noscript>
<p>
Je <em>potrebné</em> zapnúť Javascript na prezeranie tejto webovej stránky pre potreby interaktívnej mapy.
</noscript>
</div>
<div class="attribution">
Smerovač: <a href="http://www.routino.org/" target="routino">Routino</a>
|
Geo dáta: <span id="attribution_data"></span>
|
Dlaždice: <span id="attribution_tile"></span>
</div>
</div>

</body>

</html>
